aplicaciones/facturacion/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    # Tipos de Movimientos
    path('facturacion/tipos-movimientos-lista/', views.fac_tipos_movimientos_lista, name = 'tipos-mov-lista'),
    path('facturacion/tipos-movimientos-crear/', views.fac_tipos_movimientos_crear, name = 'tipos-mov-crear'),
    path('facturacion/tipos-movimientos-modificar/<cod_movimiento>', views.fac_tipos_movimientos_modificar, name = 'tipos-mov-modificar'),
    path('facturacion/tipos-movimientos-eliminar/<cod_movimiento>', views.fac_tipos_movimientos_eliminar, name = 'tipos-mov-eliminar'),
]

titanium/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.administracion.urls')),
    path('', include('aplicaciones.inventarios.urls')),
    path('', include('aplicaciones.facturacion.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Esta ultima linea es para relacionar las imagenes: MEDIA_URL y MEDIA_ROOT que estan definidas en el
# archivo settings.py del proyecto

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/facturacion/models.py
from typing import Any, Dict, Tuple
from django.db import models

# Atajos DJaneiro 
# mchar + tab   para columnas de tipo char
# fk + tab      para llaves foraneas
# mdecimal      para columnas de tipo decimal
# mint          para columnas enteras
# mimg          para columnas de imagen

# --------------------------------------------------------------------------------------------------------
# --- Creación de Modelos de Tablas de Nuestra Base de Datos
# --------------------------------------------------------------------------------------------------------

Opciones_Efecto = [
  ('+', 'Aumenta Saldo'),
  ('-', 'Disminuye Saldo'),
]

class fac_tipos_movimientos(models.Model):
    cod_movimiento = models.CharField('Código Movimiento', max_length=3, primary_key=True)
    nbr_movimiento = models.CharField('Nombre Movimiento', max_length=50)
    lsv_efecto = models.CharField('Efecto del Movimiento', max_length=1, choices=Opciones_Efecto, default='+')
    str_serie_doc = models.CharField('Serie del Documento', max_length=12)
    num_correlativo_actual = models.BigIntegerField()

    class Meta:
        db_table = 'fac_tipos_movimientos'

    def __str__(self):
        return self.nbr_movimiento

aplicaciones/facturacion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from .models import fac_tipos_movimientos

from .formularios import TiposMovForm

# Importamos la mensajería de DJango
from django.contrib import messages

# Importamos el Paginator desde django
from django.core.paginator import Paginator
from django.http import Http404

# Importamos el login_required para autorizacion de vistas
from django.contrib.auth.decorators import login_required, permission_required

# Creacion de Vistas

# -------------------------------------------------------------------------------------------
# --- Tipos de Movimientos
# -------------------------------------------------------------------------------------------

@permission_required('facturacion.view_inv_tipos_movimientos')
def fac_tipos_movimientos_lista (request):
    lista = fac_tipos_movimientos.objects.all().order_by('nbr_movimiento')
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(lista, 6)
        lista = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity': lista,
        'paginator': paginator
    }

    return render(request, 'facturacion/tipos-movimientos-lista.html', data)

@permission_required('facturacion.add_inv_tipos_movimientos')
def fac_tipos_movimientos_crear(request):
    form = TiposMovForm(request.POST or None, request.FILES or None)
    if form.is_valid() and request.POST:
        form.save()
        messages.success(request, 'Tipo de Movimiento Adicionado Correctamente !!!')
        return redirect('/facturacion/tipos-movimientos-lista/')
    return render(request, 'facturacion/tipos-movimientos-crear.html', {'formulario': form})

@permission_required('facturacion.change_inv_tipos_movimientos')
def fac_tipos_movimientos_modificar(request, cod_movimiento):
    TiposMov = get_object_or_404(fac_tipos_movimientos, cod_movimiento = cod_movimiento)
    form = TiposMovForm(request.POST or None, request.FILES or None, instance=TiposMov)
    if form.is_valid() and request.POST:
        form.save()
        messages.success(request, f'Tipo de Movimiento { TiposMov.nbr_movimiento } Modificado Correctamente !!!')
        return redirect('/facturacion/tipos-movimientos-lista/')
    return render(request, 'facturacion/tipos-movimientos-modificar.html', {'formulario': form})

@permission_required('facturacion.delete_inv_tipos_movimientos')
def fac_tipos_movimientos_eliminar(request, cod_movimiento):
    TiposMov = get_object_or_404(fac_tipos_movimientos, cod_movimiento = cod_movimiento)
    TiposMov.delete()
    messages.success(request, f'Tipo de Movimiento { TiposMov.nbr_movimiento } Eliminado Correctamente !!!')
    return redirect('/facturacion/tipos-movimientos-lista/')

templates/facturacion/tipos-movimientos-crear.html
{% extends 'plantilla_base.html' %}

{% block titulo %} 
    Adicionar Tipos de Movimientos
{% endblock titulo %} 

{% block contenido %}

    {% load crispy_forms_tags %}

    <form enctype = "multipart/form-data" method = "post">

        <div class="col-12 col-md-6 offset-md-3">

            <!-- Se le indica a Django con esta llave que este formulario le pertenece a la misma aplicacion -->
            {% csrf_token %}

            <!-- bs5-card-head-foot -->
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title text-center">Adición de Tipos de Movimientos</h4>
                </div>

                <div class="text-center">
                    <br>
                    <!-- bs5-button-input -->
                    <input name="" id="" class="btn btn-success" type="submit" value="Enviar Información">

                    <input name="" id="" class="btn btn-secondary" type="reset" value="Limpiar">

                    <a name="" id="" class="btn btn-danger" href="{{ request.META.HTTP_REFERER }}" role="button">Cancelar</a>
                    <hr>
                </div>

                <div class="card-body">

                    {{ formulario | crispy }}

                </div>
                <div class="card-footer text-muted">

                </div>
            </div>
        </div>
    </form>

{% endblock contenido %}

templates/facturacion/tipos-movimientos-lista.html
{% extends 'plantilla_base.html' %}

{% block titulo %}
    Tipos de Movimientos
{% endblock %}

{% block js %}
    <script>
        function eliminar(cod_movimiento) {
          Swal.fire({
            'title': 'Desea Confirmar Eliminación ?',
            'text': 'Tipo de Movimiento No Podrá ser Recuperado !!!',
            'icon': 'question',
            'showCancelButton': true,
            'confirmButtonText': 'Si, Eliminar',
            'cancelButtonText': 'No, Cancelar',
            'reverseButtons': true,
            'cancelButtonColor': '#7C9E41',
            'confirmButtonColor': '#dc3545'
            })
            .then(function(result) {
                if(result.isConfirmed) {
                    window.location.href = 'http://' + window.location.host + "/facturacion/tipos-movimientos-eliminar/" + cod_movimiento
                }
            })
        }
    </script>
{% endblock js %}

{% block contenido %}

    <!-- Esto se hace con bs5-card-head-foot -->
    <div class="card">
        <div class="card-header">
            <div class="btn-toolbar container-fluid">

                {% if perms.facturacion.add_fac_tipos_movimientos %}
                    <!-- Esto se hace con bs5-button-a -->
                    <a name="" id="" class="btn btn-success me-2" href="{% url 'tipos-mov-crear' %}" role="button">Agregar Tipo de Movimiento</a>
                {% endif %}   
                <form class="d-flex">
                    <input class="form-control me-2 col-lg-4" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
            </div>
        </div>
        <div class="card-body">
            <h4 class="card-title text-center">Lista de Tipos de Movimientos</h4>

            <!-- Esto se hace utilizando bs5-table -->
            <div class="table-responsive">
                <table class="table table-primary table-striped"">
                    <thead>
                        <tr class="text-center">
                            <th scope="col">Código Movimiento</th>
                            <th scope="col">Descripción del Tipo de Movimiento</th>
                            <th scope="col">Serie del Documento</th>
                            <th scope="col">Correlativo Actual</th>
                            <th scope="col">Operaciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for tipomov in entity %}
                            <tr class="">
                                <td class="text-center" scope="row">{{ tipomov.cod_movimiento }}</td>
                                <td>{{ tipomov.nbr_movimiento }}</td>
                                <td>{{ tipomov.str_serie_doc }}</td>
                                <td>{{ tipomov.num_correlativo_actual }}</td>
                                <td class="text-center">
                                    {% if perms.facturacion.change_fac_tipos_movimientos %}
                                        <a class="btn btn-sm btn-info" href="{% url 'tipos-mov-modificar' tipomov.cod_movimiento %}" role="button">
                                            <i class="fa-solid fa-pencil" ></i> 
                                        </a>
                                    {% endif %}   
                                    |
                                    {% if perms.facturacion.delete_fac_tipos_movimientos %}
                                        <a class="btn btn-sm btn-danger" href="#" onclick="eliminar('{{ tipomov.cod_movimiento }}')" role="button">
                                            <i class="fa-solid fa-trash-can" ></i> 
                                        </a>
                                    {% endif %}   
                                </td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>

                <hr>
                <div>
                    {% include 'paginator.html' %}
                </div>

            </div>
        </div>
        <div class="card-footer text-muted text-center">
            <!-- Todos los Derechos Reservados - GammaSoft -->
        </div>
    </div>

{% endblock %}

templates/facturacion/tipos-movimientos-modificar.html
{% extends 'plantilla_base.html' %}

{% block titulo %} 
    Modificar Tipos de Movimientos
{% endblock titulo %} 

{% block contenido %}

    {% load crispy_forms_tags %}

    <form enctype = "multipart/form-data" method = "post">
        <div class="col-12 col-md-6 offset-md-3">

            <!-- Se le indica a Django con esta llave que este formulario le pertenece a la misma aplicacion -->
            {% csrf_token %}

            <!-- bs5-card-head-foot -->
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title text-center">Modificación de Tipos de Movimientos</h4>
                </div>

                <div class="text-center">
                    <br>
                    <!-- bs5-button-input -->
                    <input name="" id="" class="btn btn-success" type="submit" value="Enviar Información">

                    <input name="" id="" class="btn btn-secondary" type="reset" value="Limpiar">

                    <a name="" id="" class="btn btn-danger" href="{{ request.META.HTTP_REFERER }}" role="button">Cancelar</a>
                    <hr>
                </div>

                <div class="card-body">

                    {{ formulario | crispy }}

                </div>
                <div class="card-footer text-muted">

                </div>
            </div>
        </div>
    </form>

{% endblock contenido %}