aplicaciones/administracion/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    # Se deja el primer parametro en blanco para indicar que es el raiz del sitio y lo cargara de inicio
    path('', views.menu_principal, name = '/'),
    path('administracion/contacto/', views.contacto, name = 'contacto'),
    path('registro/', views.registro, name = 'registro'),
]

titanium/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.administracion.urls')),
    path('', include('aplicaciones.inventarios.urls')),
    path('', include('aplicaciones.facturacion.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Esta ultima linea es para relacionar las imagenes: MEDIA_URL y MEDIA_ROOT que estan definidas en el
# archivo settings.py del proyecto

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/administracion/models.py
from typing import Any, Dict, Tuple
from django.db import models

# Atajos DJaneiro 
# mchar + tab   para columnas de tipo char
# fk + tab      para llaves foraneas
# mdecimal      para columnas de tipo decimal
# mint          para columnas enteras
# mimg          para columnas de imagen

# --------------------------------------------------------------------------------------------------------
# --- Creación de Modelos de Tablas de Nuestra Base de Datos
# --------------------------------------------------------------------------------------------------------

opciones_consultas = [
  (0, 'Consulta'),
  (1, 'Reclamo'),
  (2, 'Sugerencia'),
  (3, 'Comentario'),
]

class adm_contactos(models.Model):
    nombre = models.CharField('Nombre del Contacto', max_length=50)
    correo = models.EmailField('Correo Electrónico', max_length=254)
    tipo_consulta = models.IntegerField('Tipo Consulta', choices=opciones_consultas, default=0)
    mensaje = models.TextField('Mensaje Enviado')
    avisos = models.BooleanField('Recibir Notificaciones')

    class Meta:
        db_table = 'adm_contactos'

    def __str__(self):
        return self.nombre

aplicaciones/facturacion/models.py
from typing import Any, Dict, Tuple
from django.db import models

# Atajos DJaneiro 
# mchar + tab   para columnas de tipo char
# fk + tab      para llaves foraneas
# mdecimal      para columnas de tipo decimal
# mint          para columnas enteras
# mimg          para columnas de imagen

# --------------------------------------------------------------------------------------------------------
# --- Creación de Modelos de Tablas de Nuestra Base de Datos
# --------------------------------------------------------------------------------------------------------

Opciones_Efecto = [
  ('+', 'Aumenta Saldo'),
  ('-', 'Disminuye Saldo'),
]

class fac_tipos_movimientos(models.Model):
    cod_movimiento = models.CharField('Código Movimiento', max_length=3, primary_key=True)
    nbr_movimiento = models.CharField('Nombre Movimiento', max_length=50)
    lsv_efecto = models.CharField('Efecto del Movimiento', max_length=1, choices=Opciones_Efecto, default='+')
    str_serie_doc = models.CharField('Serie del Documento', max_length=12)
    num_correlativo_actual = models.BigIntegerField()

    class Meta:
        db_table = 'fac_tipos_movimientos'

    def __str__(self):
        return self.nbr_movimiento

aplicaciones/inventarios/models.py
from typing import Any, Dict, Tuple
from django.db import models

# Atajos DJaneiro 
# mchar + tab   para columnas de tipo char
# fk + tab      para llaves foraneas
# mdecimal      para columnas de tipo decimal
# mint          para columnas enteras
# mimg          para columnas de imagen
#
# def __str_(self) define el nombre del campo que mas representa al registro

# --------------------------------------------------------------------------------------------------------
# --- Creación de Modelos de Tablas de Nuestra Base de Datos
# --------------------------------------------------------------------------------------------------------

class inv_lineas_productos(models.Model):
    cod_linea = models.CharField('Código Línea', max_length=3, primary_key=True)
    nbr_linea = models.CharField('Nombre Línea', max_length=50)

    class Meta:
        db_table = 'inv_lineas_productos'

    def __str__(self):
        return self.nbr_linea

class inv_unidades_medida(models.Model):
    cod_unidad = models.CharField('Código Unidad', max_length=3, primary_key=True)
    nbr_unidad = models.CharField('Nombre Unidad', max_length=30)

    class Meta:
        db_table = 'inv_unidades_medida'

    def __str__(self):
        return self.nbr_unidad

class inv_catalogo_productos(models.Model):
    cod_producto = models.CharField('Código Producto', max_length=20, primary_key=True)
    nbr_producto = models.CharField('Nombre Producto', max_length=60)
    cod_linea = models.ForeignKey(inv_lineas_productos, on_delete=models.PROTECT, verbose_name='Línea de Producto') 
    cod_unidad = models.ForeignKey(inv_unidades_medida, on_delete=models.PROTECT, verbose_name='Unidad de Medida')
    cod_barra = models.CharField('Código de Barra', max_length=30)
    str_imagen = models.ImageField('Imagen', upload_to='imagenes/', null=True)
    val_costo_unitario = models.DecimalField('Costo Unitario', max_digits=9, decimal_places=2)
    val_precio_venta = models.DecimalField('Precio de Venta', max_digits=9, decimal_places=2)
    num_existencia_actual = models.IntegerField('Existencia Actual')

    class Meta:
        db_table = 'inv_catalogo_productos'

    def __str__(self):
        return self.nbr_producto
    
    def delete(self, using=None, keep_parents=False):

        if self.str_imagen:
            self.str_imagen.storage.delete(self.str_imagen.name)
        
        super().delete()

class inv_cajas(models.Model):
    cod_caja = models.CharField('Código Caja', max_length=3, primary_key=True)
    nbr_caja = models.CharField('Nombre Caja', max_length=50)

    class Meta:
        db_table = 'inv_cajas'

class inv_tipos_movimientos(models.Model):
    cod_tipo_mov = models.CharField('Código Tipo Movimiento', max_length=3, primary_key=True)
    nbr_tipo_mov = models.CharField('Nombre Tipo Movimiento', max_length=50)
    lsv_efecto = models.CharField('Efecto del Movimiento', max_length=1)

    class Meta:
        db_table = 'inv_tipos_movimientos'

#class inv_correlativos_mov(models.Model):
#    cod_tipo_mov = models.ForeignKey(inv_tipos_movimientos, on_delete=models.RESTRICT, unique=True)
#    cod_caja = models.ForeignKey(inv_cajas, on_delete=models.RESTRICT, unique=True)
#    cod_serie_doc = models.CharField('Serie del Documento', max_length=20)
#    num_correlativo_doc = models.BigIntegerField('Correlativo Documento')
#    class Meta:
#        db_table = 'inv_correlativos_mov'

aplicaciones/administracion/views.py
from django.shortcuts import render, redirect

from .formularios import ContactoForm, CustomUserCreationForm

# Importamos la mensajería de DJango
from django.contrib import messages

# Importyamos estas dos funciones para autenticar usuarios manualmente
from django.contrib.auth import authenticate, login

# Creación de Vistas
def menu_principal (request):
    return render(request, 'administracion/menu_principal.html')

def contacto (request):
    form = ContactoForm(request.POST or None, request.FILES or None)
    if form.is_valid() and request.POST:
        form.save()
        messages.success(request, 'Mensaje Enviado Correctamente !!!')
        return redirect('/')
    return render(request, 'administracion/contacto.html', {'formulario': form})

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            # Autenticamos el usuario
            user = authenticate(username = formulario.cleaned_data['username'], password = formulario.cleaned_data['password1'])
            login(request, user)
            messages.success(request, 'Registro Guardado Correctamente !!!')
            return redirect(to = '/')
        data['form'] = formulario

    return render(request, 'registration/registro.html', data)

templates/administracion/contacto.html
{% extends 'plantilla_base.html' %}

{% block titulo %} 
    Contacto
{% endblock titulo %} 

{% block contenido %}

    {% load crispy_forms_tags %}

    <form enctype = "multipart/form-data" method = "post">

        <div class="col-12 col-md-6 offset-md-3">

            <!-- Se le indica a Django con esta llave que este formulario le pertenece a la misma aplicacion -->
            {% csrf_token %}

            <!-- bs5-card-head-foot -->
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title text-center">Contáctanos !!!</h4>
                </div>

                <div class="text-center">
                    <br>
                    <!-- bs5-button-input -->
                    <input name="" id="" class="btn btn-success" type="submit" value="Enviar Información">

                    <input name="" id="" class="btn btn-secondary" type="reset" value="Limpiar">

                    <a name="" id="" class="btn btn-danger" href="{{ request.META.HTTP_REFERER }}" role="button">Cancelar</a>
                    <hr>
                </div>

                <div class="card-body">

                    {{ formulario | crispy }}

                </div>
                <div class="card-footer text-muted">

                </div>
            </div>
        </div>
    </form>

{% endblock contenido %}

templates/administracion/menu_principal.html
{% load static %}

<!doctype html>
<html lang="es">

<head>
  <title>Titanium</title>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">  

  <link rel="stylesheet" type="text/css" href="{% static '/estilos/estilos.css' %}">

</head>

<body>
  <header>

    <!-- Construcción de nuestro NavBar -->
    <div class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid container">

        <a class="navbar-brand" href="#">
          <img src="static/imagenes/GS-Logo.ico" alt="" width="35" height="35">
        </a>
        <a href="#" class="navbar-brand">GammaSoft</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="nav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="#" class="nav-link">Administración</a>
            </li>

            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Inventarios</a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li>
                  <a href="#" class="dropdown-item">Configuración &raquo;</a>
                  <ul class="dropdown-menu submenu dropdown-menu-dark">
                    {% if perms.inventarios.view_inv_lineas_productos %}
                      <li>
                        <a href="{% url 'lineas-lista' %}" class="dropdown-item">Líneas de Productos</a>
                      </li>
                    {% endif %}
                    {% if perms.inventarios.view_inv_unidades_medida %}
                      <li>
                        <a href="{% url 'unidades-lista' %}" class="dropdown-item">Unidades de Medida</a>
                      </li>
                    {% endif %}
                    {% if perms.inventarios.view_inv_catalogo_productos %}
                      <li>
                        <a href="{% url 'productos-lista' %}" class="dropdown-item">Catálogo de Productos</a>
                      </li>
                    {% endif %}
                  </ul>
                </li>
                <li>
                  <a href="#" class="dropdown-item">Procesos &raquo;</a>
                  <ul class="dropdown-menu submenu dropdown-menu-dark">
                    <li>
                      <a href="#" class="dropdown-item">Movimientos de Inventarios</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="#" class="dropdown-item">Reportes &raquo;</a>
                  <ul class="dropdown-menu submenu dropdown-menu-dark">
                    <li>
                      <a href="#" class="dropdown-item">Existencias de Productos</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Kardex General</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Movimientos por Productos</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Productos sin Movimientos</a>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Facturación</a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li>
                  <a href="#" class="dropdown-item">Configuración &raquo;</a>
                  <ul class="dropdown-menu submenu dropdown-menu-dark">
                    {% if perms.facturacion.view_fac_tipos_movimientos %}
                      <li>
                        <a href="{% url 'tipos-mov-lista' %}" class="dropdown-item">Tipos de Movimientos</a>
                      </li>
                    {% endif %}
                    <li>
                      <a href="#" class="dropdown-item">Clientes</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Vendedores</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Tipos de Impuestos</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="#" class="dropdown-item">Procesos &raquo;</a>
                  <ul class="dropdown-menu submenu dropdown-menu-dark">
                    <li>
                      <a href="#" class="dropdown-item">Facturas / Créditos Fiscales</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Tickets</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="#" class="dropdown-item">Reportes &raquo;</a>
                  <ul class="dropdown-menu submenu dropdown-menu-dark">
                    <li>
                      <a href="#" class="dropdown-item">Detalle de Ventas por Productos</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Detalle de Cierre de Caja</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Resumen de Ingresos Diarios</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">Productos más Vendidos</a>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>

          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a href="{% url 'contacto' %}" class="nav-link">Contactanos</a>
            </li>
            
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">Cerrar Sesión</a>
              </li>
              <li>
                <a href="#"  class="nav-link">@{{ user.username }}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'registro' %}" class="nav-link">Registrarse</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link">Iniciar Sesión</a>
              </li>
            {% endif %}
              
          </ul>

        </div>
      </div>
    </div>
  </header>

  <main>
    <div class="container text-center col-lg-5 col-md-6 col-sm-6 col-xs-12">
      <br><br><br>

      <div class = "row">
        <figure>
          <img class="img-fluid rounded d-block m-l-none" alt="Slogan" src="{% static '/imagenes/LogoTitanium.jpg' %}">
        </figure>
      </div>

    </div>
  </main>

  <footer class="container-fluid text-center mt-4">

    <script type="text/javascript">
      var fecha = new Date();
      document.write('Todos los Derechos Reservados - GammaSoft ' + fecha.getFullYear());
    </script>

  </footer>

  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>

  {% if messages %}
            
    {% for texto in messages %}
      <script>
        Swal.fire({
          'title': 'Titanium System',
          'text': '{{ texto }}',
          'icon': 'success'
        })
      </script>
    {% endfor %}

  {% endif %}

</body>

</html>